---
# vars file for deploy_cluster_addons
home_owner: martin
#kubeconfig_path: /home/martin/.kube/admin_k8s-02-control-plane.conf
kubeconfig_path: /home/martin/.kube/admin_k8s-management-control-plane.conf

##############
###ARGOCD#####
argocd_values: /home/martin/Documents/INFRA/git/Helm_Charts/argocd/values.yaml
argocd_chart: /home/martin/Documents/INFRA/git/Helm_Charts/argocd/
argo_root_app_chart: /home/martin/Documents/INFRA/git/Helm_Charts/argocd/core-services-root-app
argo_root_app_values: /home/martin/Documents/INFRA/git/Helm_Charts/argocd/core-services-root-app/values.yaml
argocd_namespace: argocd

