#SPDX-License-Identifier: MIT-0
---
# tasks file for install_docker
- block:   
    - name: Install prerequisites
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Install keyrings
      ansible.builtin.command:
        cmd: install -m 0755 -d /etc/apt/keyrings

    - name: Add Dockers official GPG key
      ansible.builtin.command:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: a+r       
        
    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker packages
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Disable automatic updates for Docker packages
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/docker-no-update.pref
        content: |
          Package: docker-ce docker-ce-cli containerd.io
          Pin: release *
          Pin-Priority: 1001
        mode: '0644'

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Backup docker initial config
      ansible.builtin.copy:
        src: /etc/containerd/config.toml
        dest: /etc/containerd/config.toml.back
        owner: root
        group: root
        mode: '0644'
 
    - name: Create docker default config
      ansible.builtin.shell: /bin/containerd config default > /etc/containerd/config.toml

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
  become: true
