#SPDX-License-Identifier: MIT-0
---
# tasks file for configure_hosts_file
# - name: Generate hosts file locally
#   delegate_to: localhost
#   run_once: true
#   ansible.builtin.template:
#     src: templates/hosts.j2
#     dest: /tmp/hosts
#     mode: '0644'

# - name: Copy hosts file to each host
#   ansible.builtin.copy:
#     src: /tmp/hosts
#     dest: /etc/hosts
#     owner: root
#     group: root
#     mode: '0644'
#   become: true

- block:
     - name: Template hosts file
       ansible.builtin.template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
  become: true        
