---
# tasks file for deploy_cluster_addons
#####################################
#####METALLB#####
#####################################
- name: Deploy MetalLB from localhost
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  kubernetes.core.helm:
    name: metallb
    chart_ref: "{{ metallb_chart }}"
    release_namespace: "{{ metallb_namespace }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path }}"
    values_files: 
      - "{{ metallb_values }}"
    state: present
  
- name: Wait for MetalLB pods to be running
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ metallb_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"
  register: metallb_pods
  retries: 10
  delay: 10
  until: >
    metallb_pods is defined and
    metallb_pods.resources is defined and
    (
      metallb_pods.resources
      | selectattr('status.phase', 'equalto', 'Running')
      | list | length
    ) > 0

- debug:
    var: metallb_pods

- name: Deploy MetalLB IP pool
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  kubernetes.core.helm:
    name: metallb-ip-pool
    chart_ref: "{{ metallb_ippool_chart }}"
    release_namespace: "{{ metallb_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"
    values_files:
      - "{{ metallb_ippool_values }}"
    state: present

- name: Verify IP pool exists
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  kubernetes.core.k8s_info:
    api_version: metallb.io/v1beta1
    kind: IPAddressPool
    namespace: "{{ metallb_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"
  register: ippools

- ansible.builtin.debug:
    var: ippools.resources   


#####################################
#####TRAEFIK LOADBALACER#####
##################################### 
- name: Deploy Traefik from localhost
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  kubernetes.core.helm:
    name: traefik-lb
    chart_ref: "{{ traefik_chart }}"
    release_namespace: "{{ traefik_namespace }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path }}"
    values_files: 
      - "{{ traefik_values }}"
    state: present

- name: Wait for Traefik pods to be running
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ traefik_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"
  register: traefik_pods
  retries: 10
  delay: 10
  until: >
    traefik_pods is defined and
    traefik_pods.resources is defined and
    (
      traefik_pods.resources
      | selectattr('status.phase', 'equalto', 'Running')
      | list | length
    ) > 0    


#####################################
#####LONGHORN#####
##################################### 
- name: Deploy Longhorn from localhost
  delegate_to: localhost
  run_once: true
  vars:
    ansible_become: false
  kubernetes.core.helm:
    name: longhorn
    chart_ref: "{{ longhorn_chart }}"
    release_namespace: "{{ longhorn_namespace }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path }}"
    values_files: 
      - "{{ longhorn_values }}"
    state: present

