---
# tasks file for configure_proxmomx
- name: Configure Proxmox VE node
  become: true

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ proxmox_hostname }}"

    # - name: Update /etc/hosts
    #   ansible.builtin.lineinfile:
    #     dest: /etc/hosts
    #     line: "127.0.1.1 {{ proxmox_hostname }}"
    #     state: present

    - name: Remove enerprice repos
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/pve-enterprise.list
        - /etc/apt/sources.list.d/ceph.list    

    - name: Add non-subscription (community) repo
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        content: |
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Set timezone
      ansible.builtin.timezone:
        name: "{{ timezone }}"

    - name: Install basic tools
      ansible.builtin.apt:
        name:
          - htop
          - vim
          - ifupdown2
        state: present

    - name:  add alias ll = ls -l
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "alias ll='ls $LS_OPTIONS -l'"
      
    - name:  export PS1 for colorful promopt
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: 'export PS1="\[\e]0;\u@\h: \w\a\]\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$"' 