- name: Laptop backup
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    backup_dir: /mnt/backup01
    home: /home/martin
    user: martin
    backups:
      - Documents
      - Documents/mypass.kdbx
      - Music
      - Pictures
      - Videos
      - Downloads
      - .config/keepassxc/
      - .config/BraveSoftware
      - .mozilla
      - .config/Code
      - .vscode/extensions
      - .kube
      - .gitconfig
      - .git_token
      - .bash_history
      - .terraform.d
      - .terraform
      - .bashrc
      - .profile


  tasks:
    - name: Ensure backup directory exists
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'
      become: true  

    - name: Get timestamp from the system
      ansible.builtin.shell: "date +%Y-%m-%d%H-%M-%S"
      register: tstamp

    - name: Set variables
      ansible.builtin.set_fact:
        date: "{{ tstamp.stdout[0:10]}}"

    - name: System timestamp - date
      ansible.builtin.debug:
        msg:  "Current date: {{ date }}" 

    - name: Check source directory exists
      ansible.builtin.stat:
        path: "{{ home }}/{{ item }}"
      register: dir_stats
      loop: "{{ backups }}"

    - name: Backup existing directories
      ansible.builtin.command: rsync -azvh {{ home }}/{{ item }} {{ backup_dir }}_{{ date }}
      loop: "{{ backups }}"
      #when: item.stat.exists  

    
    
    
  