- name: Configure Proxmox VE node
  hosts: proxmox_hosts
  become: true

  vars:
    proxmox_hostname: homelab-server
    timezone: Europe/Prague

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ proxmox_hostname }}"

    # - name: Update /etc/hosts
    #   lineinfile:
    #     dest: /etc/hosts
    #     line: "127.0.1.1 {{ proxmox_hostname }}"
    #     state: present

    - name: Remove enerprice repos
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/pve-enterprise.list
        - /etc/apt/sources.list.d/ceph.list    

    - name: Add non-subscription (community) repo
      copy:
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        content: |
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"


    - name: Install basic tools
      apt:
        name:
          - htop
          - vim
          - ifupdown2
        state: present

    - name:  add alias ll = ls -l
      lineinfile:
        path: /root/.bashrc
        line: "alias ll='ls $LS_OPTIONS -l'"
      

    - name:  export PS1 for colorful promopt
      lineinfile:
        path: /root/.bashrc
        line: 'export PS1="\[\e]0;\u@\h: \w\a\]\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$"'  