- name: Install and configure the kubernetes cluster on linux nodes
  hosts: control_plane_management, workers_management
  gather_facts: true
  roles:
    - name: Install prerequisites_and_disable_automatic_updates
      role: install_prerequisites 

    - name: Upgrade OS
      role: install_updates
      tags: [osupdate]   

    # - name: Install checkm sw version
    #   role: check_sw_versions

    - name: Set hostnames
      role: set_hostname
      
    - name: Configure /etc/hosts file
      role: configure_hosts_file
           
    - name: Sys config
      role: system_configuration
      
    - name: Install container runtime 
      role: install_containerd 
      
    - name: Install kubernetes packages, kublet,kubeadm,kubectl
      role: install_k8s_components
      tags: [test]

    - name: Initialize k8s cluster
      role: configure_k8s_cluster   

     

     

#sometimes some VM has locked apt
#when more then 1 control plane, the final cluster has only 1 control plane because another is not joined 