- name: Install and configure the kubernetes cluster on linux nodes
  hosts: control_plane_management, workers_management
  gather_facts: true
  roles:
    - name: Install prerequisites_and_disable_automatic_updates
      role: install_prerequisites
      tags: [install_prerequisites] 

    - name: Upgrade OS
      role: install_updates
      tags: [osupdate]   

    - name: Set hostnames
      role: set_hostname
      tags: [set_hostname]
      
    - name: Configure /etc/hosts file
      role: configure_hosts_file
      tags: [configure_hosts]
           
    - name: Sys config
      role: system_configuration
      tags: [system_config]
      
    - name: Install container runtime 
      role: install_containerd
      tags: [nstall_containerd]
      
    - name: Install kubernetes packages, kublet,kubeadm,kubectl
      role: install_k8s_components
      tags: [install_k8s_components]

    - name: Initialize k8s cluster
      role: configure_k8s_cluster
      tags: [k8s_cluster_init] 

     

     

#TODO

#1) Fix issue when more then 1 control plane is in the cluster, only one control plane is joined 