- name: Install and configure the kubernetes cluster on linux nodes
  hosts: control_plane_prx, workers_prx
  roles:
    - name: Install prerequisites
      role: install_prerequisites 

    - name: Install checkm sw version
      role: check_sw_versions

    - name: Set hostnames
      role: set_hostname
      
    - name: Configure /etc/hosts file
      role: configure_hosts_file
           
    - name: Sys config
      role: system_configuration
      
    - name: Install container runtime 
      role: install_containerd 
      
    - name: Install kubernetes packages, kublet,kubeadm,kubectl
      role: install_k8s_components
      tags: [test]

    - name: Initialize k8s cluster
      role: configure_k8s_cluster   
      
