#SPDX-License-Identifier: MIT-0
---
# tasks file for configure_k8s_cluster
- name: Check if cluster is already initialiezd
  when: inventory_hostname in groups['control_plane']
  ansible.builtin.shell: kubectl get nodes
  register: cluster_status
  ignore_errors: true

- block:
  #  - name: Initialize Kubernetes
   #   when: inventory_hostname in groups['control_plane']
  #    ansible.builtin.shell: kubeadm init --pod-network-cidr=190.160.0.0/16 --kubernetes-version 1.31.7
  #    register: kubeadm_init

  #  - name: Print out output of kubeadm init
  #    ansible.builtin.debug:
  #      var: kubeadm_init
 
    - name: Register output of token list
      when: inventory_hostname in groups['control_plane']
      ansible.builtin.shell: kubeadm token list
      register: token_list

    - name: Print out token list
      ansible.builtin.debug:
        var: token_list

    - name: Generate & save join command
      when: inventory_hostname in groups['control_plane']
      ansible.builtin.shell: kubeadm token create --print-join-command > "{{ vagrant_home }}/.kube/join_cluster"

    - name: Fetch join command to /tmp
      when: inventory_hostname in groups['control_plane']  
      ansible.builtin.fetch:
        src: "{{ vagrant_home }}/.kube/join_cluster"
        dest: /tmp/join_cluster
        flat: true

    - name: Create .kube dir
      ansible.builtin.file:
        path: "{{ vagrant_home }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        
    - name: Copy kube config to ./kube
      when: inventory_hostname in groups['control_plane']
      ansible.builtin.copy:
        src: "{{ kubernetes_folder }}/admin.conf"
        dest: "{{ vagrant_home }}/.kube/config"
        owner: "{{ ansible_user }}"
        mode: '0644'
        remote_src: true
    
    - name: Apply CNI Plugin (Calico)
      when: inventory_hostname in groups['control_plane']
      ansible.builtin.shell: sudo -u {{ ansible_user }} kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.2/manifests/calico.yaml 
      register: calico_output

    - name: Print out calico 
      ansible.builtin.debug:
        var: calico_output   

    - name: Copy join command to worker nodes
      when: inventory_hostname in groups['workers']
      ansible.builtin.copy:
        src: /tmp/join_cluster
        dest: "{{ vagrant_home }}/.kube/join_cluster"
        owner: "{{ ansible_user }}"
        mode: "0744"

    - name: Join worker nodes to cluster
      when: inventory_hostname in groups['workers']
      ansible.builtin.shell: /bin/sh {{ vagrant_home }}/.kube/join_cluster
      register: join_output

    - name: Print output of join command
      ansible.builtin.debug:
        var: join_output  

        #   - name: debug
        #     ansible.builtin.debug:
        #       var: cluster_status
        # 
        #   - name: test
        #     ansible.builtin.shell: echo "hovno" > /tmp/test1
        #     #when: inventory_hostname in groups['control_plane']

  become: true
  #when: cluster_status.rc == 1 and inventory_hostname in groups['control_plane']
  


  


