#SPDX-License-Identifier: MIT-0
---
# tasks file for system_configuration
- block:
    - name: Set timezone on k8s nodes
      ansible.builtin.command: timedatectl set-timezone "Europe/Prague"   

    - name: Disable Swap (temporary)
      ansible.builtin.command: swapoff -a

    - name: Disable Swap (permanent)
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent

    - name: Load kernel modules immidietly
      ansible.builtin.command:
        cmd: modprobe {{ item }}
      with_items:
        - br_netfilter
        - overlay

    - name: Ensure modules are loaded on boot
      ansible.builtin.copy:
        dest: "{{ modules_conf }}"
        content: |
          br_netfilter
          overlay
        mode: '0644'

    - name: Template network config
      ansible.builtin.template:
        src: templates/network_conf.j2
        dest: "{{ network_conf }}"
        owner: root
        group: root
        mode: '0644'

    - name: Apply new network conf
      ansible.builtin.shell: sudo sysctl --system    
    
    # - name: Disable IPv6
    #   ansible.builtin.copy:
    #     dest: "{{ network_conf }}"
    #     content: |
    #       net.ipv6.conf.all.disable_ipv6 = 1
    #       net.ipv6.conf.default.disable_ipv6 = 1
    #       net.ipv6.conf.lo.disable_ipv6 = 1
    #     owner: root
    #     group: root
    #     mode: "0644"

    # - name: Apply sysctl settings
    #   ansible.builtin.command: sysctl --system
    #   become: true
    #   changed_when: false

    # - name: Verify IPv6 is disabled
    #   ansible.builtin.command: cat /proc/sys/net/ipv6/conf/all/disable_ipv6
    #   register: ipv6_status
    #   changed_when: false

    # - name: Show IPv6 status
    #   ansible.builtin.debug:
    #     var: ipv6_status.stdout   
          
      
  become: true          

     