---
# tasks file for install_prerequisites
- name: Install packages
  ansible.builtin.package:
    name:
      - curl
  become: true  

# - name: Update all packages
#   ansible.builtin.apt:
#     name: "*"
#     state: latest
#     update_cache: true
#   become: true  




